services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: uvicorn apps.backend.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline
    command: python libs/pipeline/main.py
    volumes:
      - .:/app
      - ./assets:/app/assets
    depends_on:
      - db
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
